site_name: xiuery
site_url: https://xiuery.com/manual
site_author: xiuery.com
site_description: 帮助手册
copyright: Copyright &copy; 2015 xiuery.com

repo_name: 'GitHub'
repo_url: https://github.com/xiuery
edit_uri: ''

docs_dir: 'docs'
site_dir: 'dist'

nav:
  - Home: 'index.md'
  - Devops:
    - Linux: devops/linux.md
    - BBR: devops/bbr.md
    - ZeroTier: devops/zerotier.md
    - Shadowsocks: devops/shadowsocks.md
    - Maven: devops/maven.md
    - Nexus: devops/nexus.md
    - Svn: devops/svn.md
    - Git: devops/git.md
    - Virtualbox: devops/virtualbox.md
  - Standard:
    - Restful: standard/restful.md
    - RPC: standard/rpc.md
  - Tech:
    - Nginx: tech/nginx.md
    - Python: tech/python.md
    - ZooKeeper: tech/zookeeper.md
    - RocketMQ: tech/rocketmq.md
    - RabbitMQ: tech/rabbitmq.md
    - xpath: tech/xpath.md
  - PHP:
    - Homestead: php/homestead.md
    - Lumen: php/lumen7.md
  - Java:
    - Base: java/index.md
    - Spring: java/spring.md
  - DB:
      - Mysql: db/mysql.md
      - Redis: db/redis.md
      - Mongodb: db/mongodb.md
  - Microservice:
      - Docker: microservice/docker.md
      - Rancher: microservice/rancher.md
      - Mesh: microservice/mesh.md
      - ELK: microservice/elk.md

theme:
    name: mkdocs
    highlightjs: true
    #include_sidebar: false
    hljs_languages:
      - yaml
      - rust

extra_css:
    - css/extra.css

