site_name: xiuery
site_url: https://xiuery.com/manual
site_author: xiuery.com
site_description: 帮助手册
copyright: Copyright &copy; 2015 xiuery.com

repo_name: 'GitHub'
repo_url: https://github.com/xiuery
edit_uri: ''

docs_dir: 'docs'
site_dir: 'dist'

nav:
  - Home: 'index.md'
  - Devops:
    - Linux: devops/linux.md
    - Centos8: devops/centos8.md
    - BBR: devops/bbr.md
    - ZeroTier: devops/zerotier.md
    - Virtualbox: devops/virtualbox.md
    - Shadowsocks: devops/shadowsocks.md
    - Svn: devops/svn.md
    - Git: devops/git.md
    - Maven: devops/maven.md
    - Nexus: devops/nexus.md
    - Nginx: devops/nginx.md
    - Python: devops/python.md
    - ZooKeeper: devops/zookeeper.md
    - RocketMQ: devops/rocketmq.md
    - RabbitMQ: devops/rabbitmq.md
    - xpath: devops/xpath.md
  - Standard:
    - Restful: standard/restful.md
    - RPC: standard/rpc.md
  - PHP:
    - PHP: php/php.md
    - Homestead: php/homestead.md
    - Laravel7: php/laravel7.md
  - Java:
    - Java: java/index.md
    - Spring: java/spring.md
  - DB:
      - Mysql: db/mysql.md
      - Redis: db/redis.md
      - Mongodb: db/mongodb.md
      - ELK: db/elk.md
  - Microservice:
      - Docker: microservice/docker.md
      - Rancher: microservice/rancher.md
      - Mesh: microservice/mesh.md

theme:
    name: mkdocs
    highlightjs: true
    #include_sidebar: false
    hljs_languages:
      - yaml
      - rust

extra_css:
    - css/extra.css

