site_name: xiuery
site_url: http://www.xiuery.com
site_author: xiuery.com
site_description: 帮助手册
copyright: xiuery.com

repo_name: 'GitHub'
repo_url: https://github.com/xiuery
edit_uri: ''

nav:
  - Home: 'index.md'
  - Tech:
    - BBR: bbr.md
    - ZeroTier: zerotier.md
    - Shadowsocks: shadowsocks.md
    - SVN: svn.md
    - xpath: xpath.md
    - Maven: maven.md
    - Nexus: nexus.md
    - ZooKeeper: zookeeper.md
    - RocketMQ: rocketmq.md

theme:
    name: mkdocs
    highlightjs: true
    #include_sidebar: false
    hljs_languages:
      - yaml
      - rust

docs_dir: 'docs'
site_dir: 'dist'




