site_name: xiuery
site_url: https://xiuery.com/manual
site_author: xiuery.com
site_description: 帮助手册
copyright: Copyright &copy; 2023 xiuery.com

repo_name: 'GitHub'
repo_url: https://github.com/xiuery
edit_uri: ''

docs_dir: 'docs'
site_dir: 'dist'

nav:
  - Home: 'index.md'
  - Base:
    - Linux: base/linux.md
    - Centos8: base/centos8.md
    - Sed: base/sed.md
    - Virtualbox: base/virtualbox.md
    - ZeroTier: base/zerotier.md
    - Shadowsocks: base/shadowsocks.md
    - xpath: base/xpath.md
  - Devops:
    - Nginx: devops/nginx.md
    - Acme.sh: devops/acme.sh.md
    - Svn: devops/svn.md
    - Git: devops/git.md
    - Gitlab: devops/gitlab.md
    - RocketMQ: devops/rocketmq.md
    - RabbitMQ: devops/rabbitmq.md
    - ZooKeeper: devops/zookeeper.md
    - Nexus: devops/nexus.md
    - Harbor: devops/harbor.md
    - Jenkins: devops/jenkins.md
  - Docker:
    - Docker: docker/docker.md
    - Docker-compose: docker/docker-compose.md
    - Rancher: docker/rancher.md
    - Mesh: docker/mesh.md
  - DB:
    - Mysql: db/mysql.md
    - Redis: db/redis.md
    - Mongodb: db/mongodb.md
    - Archery: db/archery.md
    - Metabase: db/metabase.md
    - ELK: db/elk.md
  - Python:
    - Python: python/python.md
    - Jupyter: python/jupyter.md
  - PHP:
    - PHP: php/php.md
    - Homestead: php/homestead.md
    - Laravel7: php/laravel7.md
  - Java:
    - Java: java/java.md
    - Maven: java/maven.md
    - Spring: java/spring.md
  - Others:
    - Restful: others/restful.md
    - RPC: others/rpc.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
      - yaml
      - rust
    include_homepage_in_sidebar: true
    collapse_navigation: true
    titles_only: true
    sticky_navigation: true

extra_css:
    - css/extra.css

