FROM 10.0.0.119:8082/library/php:5.6-fpm
LABEL author=xiuery

ENV TZ Asia/Shanghai

# 安装模块
RUN docker-php-ext-install mysql \
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install mysqli \
	&& pecl install redis-4.0.1 \
	&& docker-php-ext-enable redis
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-install -j$(nproc) iconv \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install -j$(nproc) gd

# 自定义配置
ENV ETC_PATH /usr/local/etc
COPY ./docker/php-fpm-56 $ETC_PATH
RUN rm -f $ETC_PATH/Dockerfile

# 创建日志目录
ENV LOG_DIR /usr/local/log/
RUN mkdir -p $LOG_DIR

# 项目代码
ENV PROJECT /var/www/html/project
RUN mkdir -p $PROJECT
COPY . $PROJECT
RUN cp -f $PROJECT/lib/config-prod.inc.php $PROJECT/lib/config.inc.php
RUN rm -rf $PROJECT/docker
RUN rm -f $PROJECT/Dockerfile
RUN rm -f $PROJECT/*.sql
RUN chmod -R 777 $PROJECT

# 工作目录
WORKDIR $PROJECT

# build
# docker build -t="10.0.0.119:8082/project-name:version" .
